### PR TITLE
default color is shadcn primary color

### PR DESCRIPTION
**Pull request by programming-with-ia**

### CODE REVIEW

**Comment by programming-with-ia** [comment]
i am writing this code to change color of progress shadcn progress i my all projects
```css
#nprogress .bar {
  background: hsl(var(--primary)) !important;
}
```

**Review by immiProgrammer — COMMENTED** [review]
nice improvement

**Review by lexz451 — APPROVED** [review]

**Comment by lexz451** [comment]
yeah, nice improvement, merged! @programming-with-ia

**Comment by programming-with-ia** [comment]
This merged is not effected in npm package
I created new issue

https://github.com/lexz451/next-nprogress/issues/43
[https://opengraph.githubassets.com/1efd3c1a482a7c0449913e42c92066ca94963674de3ab37bdb1223bacaea84f3/lexz451/next-nprogress/issues/43]<https://github.com/lexz451/next-nprogress/issues/43>
new code is not published in npm · Issue #43 · lexz451/next-nprogress<https://github.com/lexz451/next-nprogress/issues/43>
github.com

________________________________

**Pull request merged**
